### ISSUE TITLE
Test conversion fails with - Cannot find module './build'

### ISSUE THREAD

**Issue by nkhare** [vzaccaria/gitbook2edx#5]
I used Dockefile file to setup the environment and when I try the sample I get following errors

```
root@e3e0acadbcfe:/src# ./bin/gitbook2edx gen test/javascript-master/

module.js:340
    throw err;
          ^
Error: Cannot find module './build'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/src/bin/gitbook2edx:8:11)
    at Object.<anonymous> (/src/bin/gitbook2edx:67:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by vzaccaria** [comment]
I can't reproduce the problem. Running the current Dockerfile with `docker build` and ssh'ing into it gives:

```
root@537a45622cb0:/src# ./bin/gitbook2edx gen test/javascript-master/
Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
_course/
_course/course.xml
_course/about/
_course/about/overview.html
_course/about/short_description.html
_course/static/
_course/static/client.js
_course/policies/
_course/policies/2014-spring/
_course/policies/2014-spring/grading_policy.json
```

**Comment by nkhare** [comment]
I see that in latest commit you removed  *src/bin* and thought that the install process would create it. But after creating the new image I don't see *bin* folder is getting creating. 

I don't know much of  *node.js*, so can't provide more useful info. If you want some kind of debug logs then please let me know.

**Comment by vzaccaria** [comment]
@nkhare can you try with this version?

**Comment by nkhare** [comment]
@vzaccaria thanks.This seems seems to be working. I would do a test export on *edX* and try with latest gitbook version.
